/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package piplbook;

import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.io.IOException;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author panos
 */
public class ProfileUI extends javax.swing.JFrame
{
    private mainUI main_window;
    private Person person;
    
    private boolean editPressed = false;
    
    private String profileImage= "";
    
    private final String fileSmallPersonPath = new java.io.File("").getAbsolutePath() + File.separator + "personsPhotos" + File.separator + "small_person.png";
  
    /**
     * Creates new form Profile
     */
    public ProfileUI(mainUI main, Person selectedPerson)
    {
        this.main_window = main;
        this.person = selectedPerson;
        
        initComponents();
        
        this.setTitle(person.getFirstName() + "\t" + person.getLastName());
        
        jTextField1.setText(person.getFirstName());
        jTextField2.setText(person.getLastName());
        jTextField3.setText(person.getPhone());
        jTextField4.setText(person.getAddress());
        jTextArea1.setText(person.getNotes());
        jLabel17.setText(person.getDateInsert());
        jLabel18.setText(person.getDateEdit());
        
        profileImage = person.getImagePath();

        Image in = Toolkit.getDefaultToolkit().createImage(profileImage);
        Image scaledImage = in.getScaledInstance(81,-1,Image.SCALE_FAST);
        ImageIcon scaledImageIcon = new ImageIcon(scaledImage);

        jLabel1.setIcon(scaledImageIcon);
        
        disableEditFields();
        
        // set background color to white
        getContentPane().setBackground(Color.WHITE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel2.setText("Όνομα:");

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N

        jLabel3.setText("Επώνυμο:");

        jLabel4.setText("Τηλέφωνο:");

        jLabel5.setText("Διεύθυνση:");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel6.setText("Σημειώσεις");

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/person.png"))); // NOI18N

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit.png"))); // NOI18N
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel11MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel11MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel11MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel11MouseReleased(evt);
            }
        });

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/change_photo.png"))); // NOI18N
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel12MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel12MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel12MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel12MouseReleased(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete.png"))); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel7MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel7MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel7MouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addGap(48, 48, 48))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(40, 40, 40))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(12, 12, 12)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save_changes.png"))); // NOI18N
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel13MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel13MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel13MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel13MouseReleased(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cancel.png"))); // NOI18N
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel8MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel8MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel8MouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(75, 75, 75)
                .addComponent(jLabel13)
                .addGap(79, 79, 79))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel13))
                .addContainerGap())
        );

        jLabel9.setText("δημιουργήθηκε:");

        jLabel14.setText("τελευταία επεξεργασία:");

        jLabel17.setText("00/00/0000");

        jLabel18.setText("00/00/0000");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel17))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel18)))
                                .addContainerGap())
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 574, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(36, 36, 36))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel9)
                                .addComponent(jLabel17)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(jLabel18))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 26, Short.MAX_VALUE)
                        .addComponent(jLabel10)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel11MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MousePressed
        // get the component of this evtent
        JLabel myLabel = (JLabel) evt.getComponent();

        //change the jLabel's icon
        try
        {
            myLabel.setIcon( new ImageIcon( javax.imageio.ImageIO.read(getClass().getResourceAsStream("/images/edit_selected.png")) ) );
        }
        catch(Exception e)
        {
            System.err.println(e.toString());
        }
    }//GEN-LAST:event_jLabel11MousePressed

    private void jLabel11MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseReleased
        // get the component of this evtent
        JLabel myLabel = (JLabel) evt.getComponent();

        //change the jLabel's icon
        try
        {
            myLabel.setIcon( new ImageIcon( javax.imageio.ImageIO.read(getClass().getResourceAsStream("/images/edit.png")) ) );
        }
        catch(Exception e)
        {
            System.err.println(e.toString());
        }
        
        editPressed = true;
        
        enableEditFields();
    }//GEN-LAST:event_jLabel11MouseReleased

    private void jLabel12MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MousePressed
        // get the component of this evtent
        JLabel myLabel = (JLabel) evt.getComponent();

        //change the jLabel's icon
        try
        {
            myLabel.setIcon( new ImageIcon( javax.imageio.ImageIO.read(getClass().getResourceAsStream("/images/change_photo_selected.png")) ) );
        }
        catch(Exception e)
        {
            System.err.println(e.toString());
        }
    }//GEN-LAST:event_jLabel12MousePressed

    private void jLabel12MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseReleased
        // get the component of this evtent
        JLabel myLabel = (JLabel) evt.getComponent();

        //change the jLabel's icon
        try
        {
            myLabel.setIcon( new ImageIcon( javax.imageio.ImageIO.read(getClass().getResourceAsStream("/images/change_photo.png")) ) );
        }
        catch(Exception e)
        {
            System.err.println(e.toString());
        }
        
        choosePhoto();
    }//GEN-LAST:event_jLabel12MouseReleased

    private void jLabel7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MousePressed
        // get the component of this evtent
        JLabel myLabel = (JLabel) evt.getComponent();

        //change the jLabel's icon
        try
        {
            myLabel.setIcon( new ImageIcon( javax.imageio.ImageIO.read(getClass().getResourceAsStream("/images/delete_selected.png")) ) );
        }
        catch(Exception e)
        {
            System.err.println(e.toString());
        }
    }//GEN-LAST:event_jLabel7MousePressed

    private void jLabel7MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseReleased
        // get the component of this evtent
        JLabel myLabel = (JLabel) evt.getComponent();

        //change the jLabel's icon
        try
        {
            myLabel.setIcon( new ImageIcon( javax.imageio.ImageIO.read(getClass().getResourceAsStream("/images/delete.png")) ) );
        }
        catch(Exception e)
        {
            System.err.println(e.toString());
        }
        
        deletePerson();
    }//GEN-LAST:event_jLabel7MouseReleased

    private void jLabel8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MousePressed
        // get the component of this evtent
        JLabel myLabel = (JLabel) evt.getComponent();

        //change the jLabel's icon
        try
        {
            myLabel.setIcon( new ImageIcon( javax.imageio.ImageIO.read(getClass().getResourceAsStream("/images/cancel_selected.png")) ) );
        }
        catch(Exception e)
        {
            System.err.println(e.toString());
        }
    }//GEN-LAST:event_jLabel8MousePressed

    private void jLabel8MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseReleased
        // get the component of this evtent
        JLabel myLabel = (JLabel) evt.getComponent();

        //change the jLabel's icon
        try
        {
            myLabel.setIcon( new ImageIcon( javax.imageio.ImageIO.read(getClass().getResourceAsStream("/images/cancel.png")) ) );
        }
        catch(Exception e)
        {
            System.err.println(e.toString());
        }
        
        if(editPressed)
        {
            JOptionPane.showMessageDialog(null, "Τυχόν αλλαγές που έχετε πραγματοποιήσει δεν θα αποθηκευτούν\nΠατήστε αποθήκευση αλλαγών" , "Δεν έχει γίνει αποθήκευση των αλλαγών", JOptionPane.WARNING_MESSAGE);   
        }
        else
        {
            this.dispose();
        }
    }//GEN-LAST:event_jLabel8MouseReleased

    private void jLabel13MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MousePressed
        // get the component of this evtent
        JLabel myLabel = (JLabel) evt.getComponent();

        //change the jLabel's icon
        try
        {
            myLabel.setIcon( new ImageIcon( javax.imageio.ImageIO.read(getClass().getResourceAsStream("/images/save_changes_selected.png")) ) );
        }
        catch(Exception e)
        {
            System.err.println(e.toString());
        }
    }//GEN-LAST:event_jLabel13MousePressed

    private void jLabel13MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseReleased
        // get the component of this evtent
        JLabel myLabel = (JLabel) evt.getComponent();

        //change the jLabel's icon
        try
        {
            myLabel.setIcon( new ImageIcon( javax.imageio.ImageIO.read(getClass().getResourceAsStream("/images/save_changes.png")) ) );
        }
        catch(Exception e)
        {
            System.err.println(e.toString());
        }
        
        if( editPressed )
        {
            updatePerson();
        }
    }//GEN-LAST:event_jLabel13MouseReleased

    private void jLabel8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseEntered
        // get the component of this evtent
        JLabel myLabel = (JLabel) evt.getComponent();

        //change the jLabel's icon
        try
        {
            myLabel.setIcon( new ImageIcon( javax.imageio.ImageIO.read(getClass().getResourceAsStream("/images/cancel_mouseOn.png")) ) );
        }
        catch(Exception e)
        {
            System.err.println(e.toString());
        }
    }//GEN-LAST:event_jLabel8MouseEntered

    private void jLabel8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseExited
        // get the component of this evtent
        JLabel myLabel = (JLabel) evt.getComponent();

        //change the jLabel's icon
        try
        {
            myLabel.setIcon( new ImageIcon( javax.imageio.ImageIO.read(getClass().getResourceAsStream("/images/cancel.png")) ) );
        }
        catch(Exception e)
        {
            System.err.println(e.toString());
        }
    }//GEN-LAST:event_jLabel8MouseExited

    private void jLabel13MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseEntered
        // get the component of this evtent
        JLabel myLabel = (JLabel) evt.getComponent();

        //change the jLabel's icon
        try
        {
            myLabel.setIcon( new ImageIcon( javax.imageio.ImageIO.read(getClass().getResourceAsStream("/images/save_changes_mouseOn.png")) ) );
        }
        catch(Exception e)
        {
            System.err.println(e.toString());
        }
    }//GEN-LAST:event_jLabel13MouseEntered

    private void jLabel13MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseExited
        // get the component of this evtent
        JLabel myLabel = (JLabel) evt.getComponent();

        //change the jLabel's icon
        try
        {
            myLabel.setIcon( new ImageIcon( javax.imageio.ImageIO.read(getClass().getResourceAsStream("/images/save_changes.png")) ) );
        }
        catch(Exception e)
        {
            System.err.println(e.toString());
        }
    }//GEN-LAST:event_jLabel13MouseExited

    private void jLabel12MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseEntered
        // get the component of this evtent
        JLabel myLabel = (JLabel) evt.getComponent();

        //change the jLabel's icon
        try
        {
            myLabel.setIcon( new ImageIcon( javax.imageio.ImageIO.read(getClass().getResourceAsStream("/images/change_photo_mouseOn.png")) ) );
        }
        catch(Exception e)
        {
            System.err.println(e.toString());
        }
    }//GEN-LAST:event_jLabel12MouseEntered

    private void jLabel12MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseExited
        // get the component of this evtent
        JLabel myLabel = (JLabel) evt.getComponent();

        //change the jLabel's icon
        try
        {
            myLabel.setIcon( new ImageIcon( javax.imageio.ImageIO.read(getClass().getResourceAsStream("/images/change_photo.png")) ) );
        }
        catch(Exception e)
        {
            System.err.println(e.toString());
        }
    }//GEN-LAST:event_jLabel12MouseExited

    private void jLabel7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseEntered
        // get the component of this evtent
        JLabel myLabel = (JLabel) evt.getComponent();

        //change the jLabel's icon
        try
        {
            myLabel.setIcon( new ImageIcon( javax.imageio.ImageIO.read(getClass().getResourceAsStream("/images/delete_mouseOn.png")) ) );
        }
        catch(Exception e)
        {
            System.err.println(e.toString());
        }
    }//GEN-LAST:event_jLabel7MouseEntered

    private void jLabel7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseExited
        // get the component of this evtent
        JLabel myLabel = (JLabel) evt.getComponent();

        //change the jLabel's icon
        try
        {
            myLabel.setIcon( new ImageIcon( javax.imageio.ImageIO.read(getClass().getResourceAsStream("/images/delete.png")) ) );
        }
        catch(Exception e)
        {
            System.err.println(e.toString());
        }
    }//GEN-LAST:event_jLabel7MouseExited

    private void jLabel11MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseEntered
        // get the component of this evtent
        JLabel myLabel = (JLabel) evt.getComponent();

        //change the jLabel's icon
        try
        {
            myLabel.setIcon( new ImageIcon( javax.imageio.ImageIO.read(getClass().getResourceAsStream("/images/edit_mouseOn.png")) ) );
        }
        catch(Exception e)
        {
            System.err.println(e.toString());
        }
    }//GEN-LAST:event_jLabel11MouseEntered

    private void jLabel11MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseExited
        // get the component of this evtent
        JLabel myLabel = (JLabel) evt.getComponent();

        //change the jLabel's icon
        try
        {
            myLabel.setIcon( new ImageIcon( javax.imageio.ImageIO.read(getClass().getResourceAsStream("/images/edit.png")) ) );
        }
        catch(Exception e)
        {
            System.err.println(e.toString());
        }
    }//GEN-LAST:event_jLabel11MouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables

    
    private void enableEditFields()
    {
        jTextField1.setEnabled(true);
        jTextField2.setEnabled(true);
        jTextField3.setEnabled(true);
        jTextField4.setEnabled(true);
        jTextArea1.setEnabled(true);
        
        jLabel12.setEnabled(true);
    }
    
    private void disableEditFields()
    {
        jTextField1.setEnabled(false);
        jTextField2.setEnabled(false);
        jTextField3.setEnabled(false);
        jTextField4.setEnabled(false);
        jTextArea1.setEnabled(false);
        
        jLabel12.setEnabled(false);
    }
        
    private void updatePerson()
    {
        String firstName = jTextField1.getText();
        String lastName = jTextField2.getText();
        String phone = jTextField3.getText();
        String address = jTextField4.getText();
        String notes = jTextArea1.getText();
        String image = profileImage;
        
        String dateInsert = person.getDateInsert();
        
        GregorianCalendar currentDate = new GregorianCalendar();
        int day = currentDate.get(Calendar.DAY_OF_MONTH);
        int month = currentDate.get(Calendar.MONTH)+1;
        int year = currentDate.get(Calendar.YEAR);
        int hour = currentDate.get(Calendar.HOUR);
        int minute = currentDate.get(Calendar.MINUTE);
        int second = currentDate.get(Calendar.SECOND);
        
        String dateEdit = day + "/" + month + "/" + year + ", " + hour + ":" + minute + ":" + second; 
        
        // check if there is a firstName and a lastName
        if( (main_window.utils.checkMinimal(firstName)) && main_window.utils.checkMinimal(lastName) )
        {
            // check if a field has too many characters
            if( (main_window.utils.checkEntry(firstName)) && (main_window.utils.checkEntry(lastName)) && (main_window.utils.checkEntry(phone)) && (main_window.utils.checkEntry(address)) && (main_window.utils.checkNotes(notes)) )
            {    
                // if firstName and lastName have changed, check fist if there is a conflict with another database entry and if ok then change the infos
                if( main_window.utils.changedMinimals(firstName, lastName, person) )
                {
                    // if entry not in the persons' table
                    if( !main_window.dbHandler.checkIfExists(firstName, lastName) )
                    {
                        // update person to database
                        if( main_window.dbHandler.dbUpdatePerson(person.getId(), firstName, lastName, phone, address, notes, image, dateInsert, dateEdit) )
                        {
                            JOptionPane.showMessageDialog(null, "Η αποθήκευση των αλλαγών ολοκληρώθηκε με επιτυχία", "Επιτυχής αποθήκευση αλλαγών", JOptionPane.INFORMATION_MESSAGE);
                        
                            editPressed = false;
                            
                            disableEditFields();
                            jLabel18.setText(dateEdit);

                            main_window.refreshWindow();
                        }
                        else
                        {
                            JOptionPane.showMessageDialog(null, "Η αποθήκευση των αλλαγών δεν πραγματοποιήθηκε", "Ανεπιτυχής αποθήκευση αλλαγών", JOptionPane.WARNING_MESSAGE);
                        }
                    }
                }
                else
                {
                    // update person to database
                    if( main_window.dbHandler.dbUpdatePerson(person.getId(), firstName, lastName, phone, address, notes, image, dateInsert, dateEdit) )
                    {
                        JOptionPane.showMessageDialog(null, "Η αποθήκευση των αλλαγών ολοκληρώθηκε με επιτυχία", "Επιτυχής αποθήκευση αλλαγών", JOptionPane.INFORMATION_MESSAGE);
                        
                        editPressed = false;
                            
                        disableEditFields();
                        jLabel18.setText(dateEdit);
                        
                        // refresh main window
                        main_window.refreshWindow();
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(null, "Η αποθήκευση των αλλαγών δεν πραγματοποιήθηκε", "Ανεπιτυχής αποθήκευση αλλαγών", JOptionPane.WARNING_MESSAGE);
                    }
                }
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Κάποιο πεδίο έχει ξεπεράσει το επιτρεπόμενο όριο χαρακτήρων", "Σφάλμα εισαγωγής", JOptionPane.WARNING_MESSAGE);
            }            
        }    
        else
        {
            JOptionPane.showMessageDialog(null, "Πρέπει να εσάγετε\nένα όνομα και ένα επώνυμο", "Σφάλμα εισαγωγής", JOptionPane.WARNING_MESSAGE);
        }        
    }
                
    private void deletePerson()
    {
        int reply = JOptionPane.showConfirmDialog(null, "Πρόκειται να διαγράφεται αυτόν το πελάτη από τις επαφές σας\nΕπιβεβαιώστε την επιλογή σας", "Διαγραφή πελάτη?", JOptionPane.YES_NO_OPTION);
        
        if (reply == JOptionPane.YES_OPTION)
        {
            if( main_window.dbHandler.dbDeletePerson(person.getId()) )
            {
                JOptionPane.showMessageDialog(null, "Επιτυχής διαγραφή επάφής", "Επιτυχής διαγραφή", JOptionPane.INFORMATION_MESSAGE);
 
                if( !(person.getImagePath().equals( fileSmallPersonPath ) ) )
                {
                    File photo = new File(person.getImagePath());
                    photo.delete();
                }
                
                main_window.refreshWindow();
            
                this.dispose();
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Ανεπιτυχής διαγραφή επαφής", "Ανεπιτυχής διαγραφή", JOptionPane.WARNING_MESSAGE);
            }
        }    
    }
        
    private void choosePhoto()
    {
        File photoSrc = null;
        
        JFileChooser jFileChooser = new JFileChooser();
        
        // Show dialog
        int ret = jFileChooser.showDialog(this, "Επιλογή εικόνας προφίλ");
        
        if( ret == JFileChooser.APPROVE_OPTION )
        {
            photoSrc = jFileChooser.getSelectedFile();
        }
        
        if( photoSrc != null )
        {
            String filename = main_window.utils.getMd5(person.getLastName() + person.getFirstName());
            String photoDstPath = new java.io.File("").getAbsolutePath() + File.separator + "personsPhotos" + File.separator + filename;
            File photoDst = new File(photoDstPath);
            
            String oldProfileImage = profileImage; 
            profileImage = photoDstPath;
            
            try
            {
                main_window.utils.copyFile(photoSrc, photoDst);
               
                if( !(oldProfileImage.equals( fileSmallPersonPath ) ) )
                {
                    File oldImage = new File(oldProfileImage);
                    oldImage.delete();
                }
            }
            catch (IOException e)
            {
                System.err.println(e.toString());
            }
                
            try
            {
                Image in = Toolkit.getDefaultToolkit().createImage(photoSrc.getAbsolutePath());
                Image scaledImage = in.getScaledInstance(81,-1,Image.SCALE_FAST);
                ImageIcon scaledImageIcon = new ImageIcon(scaledImage);
                
                jLabel1.setIcon(scaledImageIcon);
            }
            catch (Exception ex)
            {
                ex.printStackTrace();
            }
        }
    }
    
}
